### Base URL
http://microbloglite.us-east-2.elasticbeanstalk.com

### Step 1) Register or create new user
http://microbloglite.us-east-2.elasticbeanstalk.com/api/users
Content-Type: application/json

{
  "username": "mohammedalam",
  "fullName": "Mohammed Alam",
  "password": "qwerty123"
}
###make this request in register page

### Step 2) Login
POST http://microbloglite.us-east-2.elasticbeanstalk.com/auth/login
Content-Type: application/json

{
  "username": "mohammedalam",
  "password": "qwerty123"
}
### Need the token when login is successful
### "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vaGFtbWVkYWxhbSIsImlhdCI6MTcxODk4MzUwNCwiZXhwIjoxNzE5MDY5OTA0fQ.0x2bcAa_0s3_1442AJSNlUQffU06apYH9HxRmnxt2_k"

### Step 3) GET Users
GET http://microbloglite.us-east-2.elasticbeanstalk.com/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vaGFtbWVkYWxhbSIsImlhdCI6MTcxODk4MzUwNCwiZXhwIjoxNzE5MDY5OTA0fQ.0x2bcAa_0s3_1442AJSNlUQffU06apYH9HxRmnxt2_k


### Step 4) GET One User
GET http://microbloglite.us-east-2.elasticbeanstalk.com/api/users/mohammedalam
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vaGFtbWVkYWxhbSIsImlhdCI6MTcxODk4MzUwNCwiZXhwIjoxNzE5MDY5OTA0fQ.0x2bcAa_0s3_1442AJSNlUQffU06apYH9HxRmnxt2_k


### Step 5) Create a Post
POST http://microbloglite.us-east-2.elasticbeanstalk.com/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vaGFtbWVkYWxhbSIsImlhdCI6MTcxODk4MzUwNCwiZXhwIjoxNzE5MDY5OTA0fQ.0x2bcAa_0s3_1442AJSNlUQffU06apYH9HxRmnxt2_k
Content-Type: application/json

{
  "text": "Hello World"
}
### get an id of the post "_id": "6675a032fbf13c2cc0eaf6cf"

### Step 6) GET Posts
GET http://microbloglite.us-east-2.elasticbeanstalk.com/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vaGFtbWVkYWxhbSIsImlhdCI6MTcxODk4MzUwNCwiZXhwIjoxNzE5MDY5OTA0fQ.0x2bcAa_0s3_1442AJSNlUQffU06apYH9HxRmnxt2_k

### Step 6b) GET a Post
GET http://microbloglite.us-east-2.elasticbeanstalk.com/api/posts/6675a032fbf13c2cc0eaf6cf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vaGFtbWVkYWxhbSIsImlhdCI6MTcxODk4MzUwNCwiZXhwIjoxNzE5MDY5OTA0fQ.0x2bcAa_0s3_1442AJSNlUQffU06apYH9HxRmnxt2_k

### Step 7) DELETE Post
DELETE http://microbloglite.us-east-2.elasticbeanstalk.com/api/posts/6675a032fbf13c2cc0eaf6cf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vaGFtbWVkYWxhbSIsImlhdCI6MTcxODk4MzUwNCwiZXhwIjoxNzE5MDY5OTA0fQ.0x2bcAa_0s3_1442AJSNlUQffU06apYH9HxRmnxt2_k

### Step 8) Update User
PUT http://microbloglite.us-east-2.elasticbeanstalk.com/api/users/mohammedalam
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vaGFtbWVkYWxhbSIsImlhdCI6MTcxODk4MzUwNCwiZXhwIjoxNzE5MDY5OTA0fQ.0x2bcAa_0s3_1442AJSNlUQffU06apYH9HxRmnxt2_k
Content-Type: application/json

{
  "fullName": "MohammedAlam"
}


### Step 9) Add Like
POST http://microbloglite.us-east-2.elasticbeanstalk.com/api/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vaGFtbWVkYWxhbSIsImlhdCI6MTcxODk4MzUwNCwiZXhwIjoxNzE5MDY5OTA0fQ.0x2bcAa_0s3_1442AJSNlUQffU06apYH9HxRmnxt2_k
Content-Type: application/json

{
  "postId": "6675a3a2fbf13c2cc0eaf78b"
}

### Step 10) Delete/Remove Like
DELETE http://microbloglite.us-east-2.elasticbeanstalk.com/api/likes/6675a3a2fbf13c2cc0eaf78b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vaGFtbWVkYWxhbSIsImlhdCI6MTcxODk4MzUwNCwiZXhwIjoxNzE5MDY5OTA0fQ.0x2bcAa_0s3_1442AJSNlUQffU06apYH9HxRmnxt2_k
